### ISSUE TITLE
Steno:set >> `mix` and `through` behaviour

### ISSUE THREAD

**Issue by LFSaw** [musikinformatik/Steno#10]
It seems that mix is a `drywet` control, whereas through has no effect at all.

Documentation says:

> mix	sound level	default: 1
> through	for filters: pre vs. post level	default: 0

```
s.boot
(
t = t ?? {Steno.push};
t.quelle(\q, { |in, controls|
	Pulse.ar(1000) * LFPulse.ar(3, width: 0.04)
});
t.filter(\f, { |in, controls|
	PinkNoise.ar(Decay.ar(Impulse.ar(10), 0.01))  * controls[\env]
})
)



-- qf

// mix reacts like a drywet control. sounds to me like what is described as `through` in Steno helpfile (method set)

t.set(\f, \mix, 1) // only filter (default)
t.set(\f, \mix, 0) // only quelle

// through

t.set(\f, \through, 1, \mix, 1) // with mix==1, has no effect
t.set(\f, \through, 0, \mix, 1)

t.set(\f, \through, 1, \mix, 0) // with mix==0, has no effect
t.set(\f, \through, 0, \mix, 0)
```

**Comment by LFSaw** [comment]
@telephon can I have an opinion in this?

**Comment by telephon** [comment]
Let's discuss this when i have the occasion to test and look at the code, in a month or so.

The confusion comes perhaps from a different meaning of the two parameters in quelle and filter, and perhaps in buggy behaviour.

Normally, `through` should make a synth increasingly transparent, but i have to have another look. what's your opinion ?

**Comment by LFSaw** [comment]
`mix` behaves differently in `quelle` and `filter`, whereas `through` doesn't do anything. Let's discuss whenever you have time :) If it'll take a month, I think I need to just go ahead and develop my own fork, though...

**Comment by telephon** [comment]
I can discuss but nothing much else. Remember to check how parentheses respond to these parameters.

The bus mapping is a little delicate.

**Comment by telephon** [comment]
the difference between `mix` and `through` is in the difference between `dryIn` and `outBus`  in the `StenoSignal` class. This is where I'd look if I could

**Comment by LFSaw** [comment]
thanks for the pointer. I also started to understand what is wrong with `thorugh`: it is not possible to set it with `Steno:set` since it is excluded from that [here](https://github.com/telephon/Steno/blob/4ff9c33a7977ba943a7fbb9784231c37a51433b4/Classes/StenoSettings.sc#L35) (we should definitely make this list a static variable that resides in a more visible place...).

**Comment by telephon** [comment]
ah yes, maybe it is better to keep it internal? I don't remember what I was using it for.

**Comment by LFSaw** [comment]
I'm on it... :)
